AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: a2-Lambda
Resources:
  Lambda1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: a2-lf1-py
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./lf1
      Description: 'Photo index insertion'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::205407915465:role/CloudFormation_Lex_Lambda_APIGateway_Administrator'
      Environment:
        Variables:
          REGION: us-east-1

  Lambda2:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: a2-lf2-py
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./lf2
      Description: 'Photo search'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::205407915465:role/CloudFormation_Lex_Lambda_APIGateway_Administrator'
      Environment:
        Variables:
          REGION: us-east-1